llama2-7b:
  hf_key: "Llama-2-7b-chat-hf"
  question_start_tag: "[INST] "
  question_end_tag: " [/INST]"
  answer_tag: ""
  flash_attention2: "true"
  gradient_checkpointing: "true"
  ft_model_path: "models/pii_7B_without_target"